# Generated by Django 5.1.1 on 2024-09-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_recipepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipepost',
            name='instructions',
        ),
    ]
