# Generated by Django 5.1.1 on 2024-09-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Proba1',
        ),
        migrations.AddField(
            model_name='recipepost',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
