# Generated by Django 5.1.1 on 2024-09-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_delete_file_delete_proba1_recipepost_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='images',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
