# Generated by Django 5.1.1 on 2024-09-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_recipepost_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
